apiVersion: v1
kind: Service
metadata:
  name: strapi-service
spec:
  type: NodePort
  selector:
    app: strapi-cms
  ports:
    - port: 1337
      targetPort: 1337
      nodePort: 30001
      protocol: TCP
