apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi-cms
  labels:
    app: strapi-cms
spec:
  replicas: 3
  selector:
    matchLabels:
      app: strapi-cms
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: strapi-cms
    spec:
      containers:
        - name: strapi-cms
          image: <your_container_registry>/strapi-cms:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 1337
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 1337
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
          envFrom:
            - secretRef:
                name: strapi-env
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
      initContainers:
        - name: setup
          image: <your_container_registry>/strapi-setup:latest
          envFrom:
            - secretRef:
                name: strapi-env
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
